local config = require("tally.config")

describe("config", function()
  before_each(function()
    config.setup({})
  end)

  it("has defaults", function()
    assert.equals(300, config.options.flush_interval)
    assert.is_true(config.options.hook_keymap_set)
    assert.is_true(config.options.track.load)
    assert.same({}, config.options.passive)
  end)

  it("merges user options over defaults", function()
    config.setup({ flush_interval = 60, track = { key = false } })
    assert.equals(60, config.options.flush_interval)
    assert.is_false(config.options.track.key)
    assert.is_true(config.options.track.load)
  end)

  it("does not leak state between setup calls", function()
    config.setup({ flush_interval = 60 })
    config.setup({})
    assert.equals(300, config.options.flush_interval)
  end)

  it("matches passive patterns as substrings", function()
    config.setup({ passive = { "solarized%-osaka", "hlchunk" } })
    assert.is_true(config.is_passive("solarized-osaka.nvim"))
    assert.is_true(config.is_passive("hlchunk.nvim"))
    assert.is_false(config.is_passive("telescope.nvim"))
  end)

  it("supports anchored patterns for exact match", function()
    config.setup({ passive = { "^oil%.nvim$" } })
    assert.is_true(config.is_passive("oil.nvim"))
    assert.is_false(config.is_passive("oil.nvim.extra"))
  end)

  it("ignores malformed patterns instead of erroring", function()
    config.setup({ passive = { "[unclosed" } })
    assert.is_false(config.is_passive("telescope.nvim"))
  end)
end)
