local counter = require("tally.counter")

describe("counter", function()
  before_each(function()
    counter.drain()
  end)

  it("accumulates load counts", function()
    counter.add("flash.nvim", "load")
    counter.add("flash.nvim", "load")
    assert.equals(2, counter.peek()["flash.nvim"].load)
  end)

  it("accumulates named key and cmd counts", function()
    counter.add("telescope.nvim", "cmd", "Telescope")
    counter.add("telescope.nvim", "cmd", "Telescope")
    counter.add("flash.nvim", "key", "gs")
    local data = counter.peek()
    assert.equals(2, data["telescope.nvim"].cmd["Telescope"])
    assert.equals(1, data["flash.nvim"].key["gs"])
  end)

  it("ignores nil plugin", function()
    counter.add(nil, "key", "gs")
    assert.same({}, counter.peek())
  end)

  it("drain empties internal state", function()
    counter.add("oil.nvim", "load")
    local first = counter.drain()
    assert.equals(1, first["oil.nvim"].load)
    assert.same({}, counter.peek())
  end)

  it("drain returns a snapshot unaffected by later adds", function()
    counter.add("oil.nvim", "load")
    local snapshot = counter.drain()
    counter.add("oil.nvim", "load")
    assert.equals(1, snapshot["oil.nvim"].load)
  end)
end)
